# Generated by Django 3.2.5 on 2022-04-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('owner_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
